import Head from "next/head";
import styles from "../styles/pages/Home.module.css";
import NudeLayout from "../components/layouts/NudeLayout";
import Navbar from "../components/Navbar";
import Link from "next/link";
import { menuItems } from "../utils/data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Songna Choi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.wrapper}>
          <div className={styles.leftContainer}>
            <div className={styles.content}>
              <h1>Songna Choi </h1>
              <p className={styles.subText}>
                Pronounced as <span>Song-nah</span>
              </p>
              <p className={styles.para}>
                I enjoy developing aesthetic and fun user experience.
              </p>
            </div>
          </div>
          <div className={styles.rightContainer}>
            <Link href="/projects">
              <a>
                <h1>Projects</h1>
              </a>
            </Link>
            <Link href="/about">
              <a>
                <h1>About</h1>
              </a>
            </Link>
            <Link href="/contact">
              <a>
                <h1>Contact</h1>
              </a>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(Home) {
  return <NudeLayout>{Home}</NudeLayout>;
};
